global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'monitor-node'
    scrape_interval: 3s
    scrape_timeout: 3s
    static_configs:
      - targets: ['localhost:9300']
  - job_name: 'monitor-gpu'
    scrape_interval: 3s
    scrape_timeout: 3s
    static_configs:
      - targets: ['localhost:9400']
