apiVersion: v1
kind: Service
metadata:
  labels: {app: bexhoma, component: monitoring, configuration: default, experiment: default}
  name: bexhoma-service-monitoring-default
spec:
  clusterIP: None # Headless service
  ports:
  - {port: 9300, protocol: TCP, name: port-monitoring, targetPort: 9300}
  selector: {app: bexhoma, component: monitoring, configuration: default, experiment: default}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels: {app: bexhoma, component: monitoring, configuration: default, experiment: default}
  name: bexhoma-monitoring-default
spec:
  selector:
    matchLabels:
      name: bexhoma-monitoring-default
      app: bexhoma
      component: monitoring
      configuration: default
      experiment: default
  template:
    metadata:
      labels:
        name: bexhoma-monitoring-default
        app: bexhoma
        component: monitoring
        configuration: default
        experiment: default
      name: bexhoma-monitoring-default
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - {name: dockerhub}
      tolerations:
      - key: "nvidia.com/gpu"
        effect: "NoSchedule"
      containers:
      - name: cadvisor
        image: gcr.io/cadvisor/cadvisor:v0.47.0
        args: ["--port", "9300", "--storage_duration", "20m0s", "--docker_only", "true", "--disable_metrics", "disk,network,tcp,advtcp,udp,sched,process,hugetlb", "--application_metrics_count_limit", "30", "--housekeeping_interval", "5s"]
        ports:
        - containerPort: 9300
          #hostPort: 9300
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 150m
            memory: 200Mi
        volumeMounts:
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        - name: var-run
          mountPath: /var/run
          readOnly: true
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: docker
          mountPath: /var/lib/docker
          readOnly: true
        - name: disk
          mountPath: /dev/disk
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rootfs
        hostPath:
          path: /
      - name: var-run
        hostPath:
          path: /var/run
      - name: sys
        hostPath:
          path: /sys
      - name: docker
        hostPath:
          path: /var/lib/docker
      - name: disk
        hostPath:
          path: /dev/disk
