apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: {app: bexhoma, component: sut, configuration: default, experiment: default}
  name: bexhoma-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: shared
---
apiVersion: v1
kind: Service
metadata:
  labels: {app: bexhoma, component: sut, configuration: default, experiment: default}
  name: bexhoma-service
spec:
  ports:
  - {port: 9091, protocol: TCP, name: port-dbms, targetPort: 3306}
  - {port: 9300, protocol: TCP, name: port-monitoring, targetPort: 9300}
  selector: {app: bexhoma, component: sut, configuration: default, experiment: default}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {app: bexhoma, component: sut, configuration: default, experiment: default}
  name: bexhoma-deployment-mariadb
spec:
  replicas: 1
  selector:
    matchLabels: {app: bexhoma, component: sut, configuration: default, experiment: default}
  template:
    metadata:
      labels: {app: bexhoma, component: sut, configuration: default, experiment: default}
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - {name: dockerhub}
      nodeSelector:
      tolerations:
      #- key: "nvidia.com/gpu"
      #  effect: "NoSchedule"
      containers:
      - name: dbms
        image: mariadb:11.4.7
        #image: mariadb:11.4.2
        #image: mariadb:10.5.8
        #args: ["--innodb_log_buffer_size", "17179869184", "--innodb-write-io-threads", "16", "--innodb-log-file-size", "4294967296", "--LimitMEMLOCK", "16M"]
        #args: ["--innodb_log_buffer_size", "17179869184", "--innodb-write-io-threads", "16", "--innodb-log-file-size", "4294967296"]
        args:
          # --- I/O Threading ---
          - "--innodb-read-io-threads=64"         # Use all cores for read I/O
          - "--innodb-write-io-threads=64"        # Use all cores for write I/O
          # --- Async I/O ---
          - "--innodb-use-native-aio=0"           # CephFS-compatible async I/O
          # --- Buffer Pool (memory use) ---
          - "--innodb-buffer-pool-size=256G"      # 256G out of 500G
          - "--innodb-buffer-pool-chunk-size=2G"  # Logical chunking
          # --- I/O Capacity ---
          - "--innodb-io-capacity=200"            # CephFS-friendly
          - "--innodb-io-capacity-max=1000"       # Allow bursts
          # --- Redo Log ---
          - "--innodb-log-buffer-size=1G"         # Bigger buffer for commits
          # --- Transaction Commit Behavior ---
          - "--innodb-flush-log-at-trx-commit=2"  # Good for OLAP
          - "--sync-binlog=0"                     # Skip fsync on binlog
          # --- Temporary Tables ---
          - "--tmp-table-size=1G"                 # Avoid disk spills
          - "--max-heap-table-size=1G"            # In-memory tables
          # --- Doublewrite Buffer ---
          - "--innodb-doublewrite=0"              # Disable on CephFS
        env:
          - {name: MYSQL_ALLOW_EMPTY_PASSWORD, value: 'yes'}
        readinessProbe: #mysqladmin ping > /dev/null 2>&1 && echo "MySQL server is running." || echo "MySQL server is not running."
          exec:
            command: [
              "/bin/sh", 
              "-c", 
              "if mariadb -e 'SELECT 1+1;'; then exit 0; else exit 1; fi"
            ]
          initialDelaySeconds: 15
          periodSeconds: 60
          successThreshold: 3
        ports:
        - {containerPort: 3306}
        - {containerPort: 9000}
        resources:
          limits: {cpu: 16000m, memory: 128Gi}
          requests: {cpu: 1000m, memory: 1Gi}
          #, ephemeral-storage: "1536Gi"}
        volumeMounts:
        - {mountPath: /data, name: benchmark-data-volume}
        - {mountPath: /var/lib/mysql, name: benchmark-storage-volume}
      - name: cadvisor
        image: gcr.io/cadvisor/cadvisor:v0.47.0
        args: ["--port", "9300", "--storage_duration", "20m0s", "--docker_only", "true", "--disable_metrics", "disk,network,tcp,advtcp,udp,sched,process,hugetlb", "--application_metrics_count_limit", "30", "--housekeeping_interval", "5s"]
        ports:
        - containerPort: 9300
          #hostPort: 9300
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 150m
            memory: 200Mi
        volumeMounts:
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        - name: var-run
          mountPath: /var/run
          readOnly: true
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: docker
          mountPath: /var/lib/docker
          readOnly: true
        - name: disk
          mountPath: /dev/disk
          readOnly: true
      volumes:
      - name: benchmark-data-volume
        persistentVolumeClaim: {claimName: bexhoma-data}
      - name: benchmark-storage-volume
        persistentVolumeClaim: {claimName: bexhoma-storage}
      - name: rootfs
        hostPath:
          path: /
      - name: var-run
        hostPath:
          path: /var/run
      - name: sys
        hostPath:
          path: /sys
      - name: docker
        hostPath:
          path: /var/lib/docker
      - name: disk
        hostPath:
          path: /dev/disk
