apiVersion: v1
kind: Service
metadata:
  labels: {app: bexhoma, component: sut, configuration: default, experiment: default}
  name: bexhoma-service
spec:
  ports:
  - {port: 9091, protocol: TCP, name: port-dbms, targetPort: 6274}
  - {port: 9400, protocol: TCP, name: port-dcgm, targetPort: 9400}
  - {port: 9300, protocol: TCP, name: port-monitoring, targetPort: 9300}
  selector: {app: bexhoma, component: sut, configuration: default, experiment: default}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {app: bexhoma, component: sut, configuration: default, experiment: default}
  name: bexhoma-deployment-omnisci
spec:
  replicas: 1
  selector:
    matchLabels: {app: bexhoma, component: sut, configuration: default, experiment: default}
  template:
    metadata:
      labels: {app: bexhoma, component: sut, configuration: default, experiment: default}
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - {name: dockerhub}
      nodeSelector:
      tolerations:
      - key: "nvidia.com/gpu"
        effect: "NoSchedule"
      containers:
      - env:
        - {name: CUDA_CACHE_DISABLE, value: '0'}
        - {name: CUDA_CACHE_MAXSIZE, value: '4294967296'}
        #image: omnisci/core-os-cuda:v5.4.0
        image: perdelt/dbms:omnisci
        name: dbms
        ports:
        - {containerPort: 6274}
        resources:
          limits: {cpu: 16000m, memory: 128Gi, nvidia.com/gpu: 1}
          requests: {cpu: 16000m, memory: 128Gi}
        volumeMounts:
        - {mountPath: /data, name: benchmark-data-volume}
      - image: nvidia/dcgm-exporter:1.7.2
        name: dcgm-exporter
        env:
        - name: "DCGM_EXPORTER_PORT"
          value: "9400"
        ports:
        - name: gpu-metrics
          containerPort: 9400
          hostPort: 9400
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - name: pod-gpu-resources
          readOnly: true
          mountPath: /var/lib/kubelet/pod-resources
      - name: cadvisor
        #image: k8s.gcr.io/cadvisor:v0.30.2
        image: gcr.io/cadvisor/cadvisor:v0.36.0
        args: ["--port", "9300", "--storage_duration", "20m0s", "--docker_only", "true", "--disable_metrics", "disk,network,tcp,advtcp,udp,sched,process,hugetlb", "--application_metrics_count_limit", "30", "--housekeeping_interval", "5s"]
        ports:
        - containerPort: 9300
          hostPort: 9300
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 150m
            memory: 200Mi
        volumeMounts:
        - mountPath: /rootfs
          name: rootfs
          readOnly: true
        - mountPath: /var/run
          name: var-run
          readOnly: true
        - mountPath: /sys
          name: sys
          readOnly: true
        - mountPath: /var/lib/docker
          name: docker
          readOnly: true
        - mountPath: /dev/disk
          name: disk
          readOnly: true
      volumes:
      - name: benchmark-data-volume
        persistentVolumeClaim: {claimName: bexhoma-data}
      - hostPath:
          path: /
        name: rootfs
      - hostPath:
          path: /var/run
        name: var-run
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /var/lib/docker
        name: docker
      - hostPath:
          path: /dev/disk
        name: disk
      - name: proc
        hostPath:
          path: /proc
      - name: pod-gpu-resources
        hostPath:
          path: /var/lib/kubelet/pod-resources
      #- name: gpu-metrics
      #  emptyDir:
      #    medium: Memory
      #- name: collector-textfiles
      #  emptyDir:
      #    medium: Memory
