apiVersion: v1
kind: Service
metadata:
  labels: {app: bexhoma, component: sut, configuration: default, experiment: default}
  name: bexhoma-sut
spec:
  ports:
  - {port: 9091, protocol: TCP, name: port-dbms, targetPort: 50000}
  - {port: 9300, protocol: TCP, name: port-monitoring, targetPort: 9300}
  selector: {app: bexhoma, component: sut, configuration: default, experiment: default}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {app: bexhoma, component: sut, configuration: default, experiment: default}
  name: bexhoma-sut-monetdb
spec:
  replicas: 1
  selector:
    matchLabels: {app: bexhoma, component: sut, configuration: default, experiment: default}
  template:
    metadata:
      labels: {app: bexhoma, component: sut, configuration: default, experiment: default}
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - {name: dockerhub}
      nodeSelector:
      tolerations:
      - key: "nvidia.com/gpu"
        effect: "NoSchedule"
      containers:
      - name: dbms
        #image: perdelt/dbms:monetdb
        image: monetdb/monetdb:Oct2020-SP3
        #image: monetdb/monetdb:Oct2020-SP2
        #image: monetdb/monetdb-r-docker:11.31.7
        ports:
        - {containerPort: 50000}
        #command: ["printf "user=monetdb\npassword=monetdb\nlanguage=sql" > .monetdb"]
        resources:
          limits: {cpu: 16000m, memory: 128Gi}
          requests: {cpu: 16000m, memory: 128Gi}
        volumeMounts:
        - {mountPath: /data, name: benchmark-data-volume}
      - name: cadvisor
        #image: k8s.gcr.io/cadvisor:v0.30.2
        image: gcr.io/cadvisor/cadvisor:v0.36.0
        args: ["--port", "9300", "--storage_duration", "20m0s", "--docker_only", "true", "--disable_metrics", "disk,network,tcp,advtcp,udp,sched,process,hugetlb", "--application_metrics_count_limit", "30", "--housekeeping_interval", "5s"]
        securityContext:
          privileged: true
        ports:
        - containerPort: 9300
          hostPort: 9300
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 150m
            memory: 200Mi
        volumeMounts:
        - mountPath: /rootfs
          name: rootfs
          readOnly: true
        - mountPath: /var/run
          name: var-run
          readOnly: true
        - mountPath: /sys
          name: sys
          readOnly: true
        - mountPath: /var/lib/docker
          name: docker
          readOnly: true
        - mountPath: /dev/disk
          name: disk
          readOnly: true
      volumes:
      - name: benchmark-data-volume
        persistentVolumeClaim: {claimName: bexhoma-data}
      - hostPath:
          path: /
        name: rootfs
      - hostPath:
          path: /var/run
        name: var-run
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /var/lib/docker
        name: docker
      - hostPath:
          path: /dev/disk
        name: disk
      - name: proc
        hostPath:
          path: /proc
