apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: {app: bexhoma, component: sut, configuration: default, experiment: default}
  name: bexhoma-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: shared
---
apiVersion: v1
kind: Service
metadata:
  labels: {app: bexhoma, component: sut, configuration: default, experiment: default}
  name: bexhoma-service
spec:
  ports:
  - {port: 9091, protocol: TCP, name: port-dbms, targetPort: 6379}
  - {port: 9300, protocol: TCP, name: port-monitoring, targetPort: 9300}
  - {port: 16379, protocol: TCP, name: port-bus, targetPort: 16379}
  selector: # {app: bexhoma, component: worker, configuration: default, experiment: default}
    statefulset.kubernetes.io/pod-name: bexhoma-worker-0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {app: bexhoma, component: sut, configuration: default, experiment: default}
  name: bexhoma-deployment-redis
spec:
  replicas: 1
  selector:
    matchLabels: {app: bexhoma, component: sut, configuration: default, experiment: default}
  template:
    metadata:
      labels: {app: bexhoma, component: sut, configuration: default, experiment: default}
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - {name: dockerhub}
      nodeSelector:
      tolerations:
      #- key: "nvidia.com/gpu"
      #  effect: "NoSchedule"
      terminationGracePeriodSeconds: 180
      containers:
      - name: dbms
        image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.37.0
        ports:
          - containerPort: 6379
        ports:
          - containerPort: 6379
            name: server
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          #runAsNonRoot: true
          #runAsUser: 1000
          #runAsGroup: 1000
          #capabilities:
          #  drop:
          #    - ALL
          readOnlyRootFilesystem: false
        resources:
          limits: {cpu: 16000m, memory: 128Gi}
          requests: {cpu: 1000m, memory: 1Gi}
          #, ephemeral-storage: "1536Gi"}
---
apiVersion: v1
kind: Service
metadata:
  name: bexhoma-worker
  labels: {app: bexhoma, component: worker, configuration: default, experiment: default}
  annotations:
spec:
  ports:
  - {port: 6379, protocol: TCP, name: port-dbms, targetPort: 6379}
  - {port: 16379, protocol: TCP, name: port-bus, targetPort: 16379}
  publishNotReadyAddresses: true
  clusterIP: None
  selector: {app: bexhoma, component: worker, configuration: default, experiment: default}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bexhoma-worker
  labels: {app: bexhoma, component: worker, configuration: default, experiment: default}
spec:
  serviceName: bexhoma-workers
  replicas: 3
  selector:
    matchLabels:
      {app: bexhoma, component: worker, configuration: default, experiment: default}
  template:
    metadata:
      labels: {app: bexhoma, component: worker, configuration: default, experiment: default}
    spec:
      nodeSelector:
      tolerations:
      terminationGracePeriodSeconds: 60
      containers:
      - name: dbms
        image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.37.0
        command:
          - sh
          - -c
          - |
            ORDINAL=${POD_NAME##*-}

            if [ "$ORDINAL" -eq 0 ]; then
              echo "Starting as MASTER ($POD_NAME)"
              exec dragonfly --logtostderr
            else
              MASTER="${STATEFULSET_NAME}-0.${BEXHOMA_WORKER_SERVICE}:6379"
              echo "Starting as REPLICA of $MASTER"
              exec dragonfly --logtostderr --replicaof=$MASTER
            fi
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: STATEFULSET_NAME
            value: bexhoma-worker
          - name: BEXHOMA_WORKER_SERVICE
            value: bexhoma-workers
        ports:
          - containerPort: 6379
            name: server
        resources:
          limits: {cpu: 16000m, memory: 64Gi}
          requests: {cpu: 16000m, memory: 64Gi}
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: bxw
          mountPath: /data
      volumes:
      - name: bxw
        persistentVolumeClaim: {claimName: bxw}
  volumeClaimTemplates:
  - metadata:
      name: bxw
      labels: {app: bexhoma, component: worker, configuration: default, experiment: default}
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 100Gi
      storageClassName: shared
