apiVersion: v1
kind: Service
metadata:
  labels: {app: bexhoma, component: messagequeue}
  name: bexhoma-messagequeue
spec:
  ports:
  - {port: 6379, protocol: TCP, name: port-redis, targetPort: 6379}
  selector: {app: bexhoma, component: messagequeue}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {app: bexhoma, component: messagequeue}
  name: bexhoma-messagequeue
spec:
  replicas: 1
  selector:
    matchLabels: {app: bexhoma, component: messagequeue}
  template:
    metadata:
      labels: {app: bexhoma, component: messagequeue}
    spec:
      containers:
        - name: master
          image: redis
          env:
            - name: MASTER
              value: "true"
          ports:
            - containerPort: 6379
          securityContext:
            allowPrivilegeEscalation: false
            #runAsNonRoot: true
            #runAsUser: 1000
            #runAsGroup: 1000
            #capabilities:
            #  drop:
            #    - ALL
            readOnlyRootFilesystem: false
