apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bexhoma-data
  labels: {app: bexhoma, component: data-source, configuration: default, experiment: default}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  #storageClassName: shared
---
apiVersion: batch/v1
kind: Job
metadata:
  labels: {app: bexhoma, component: data-source, configuration: default, experiment: default, client: default}
  name: bexhoma-init-data
spec:
  template:
    metadata:
      labels: {app: bexhoma, component: data-source, configuration: default, experiment: default, client: default}
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - name: private-registry-auth
      tolerations:
      #- key: "nvidia.com/gpu"
      #  effect: "NoSchedule"
      containers:
      - name: data-init
        image: perdelt/bexhoma:data-tpch-1
        #imagePullPolicy: Always
        resources:
          limits: {cpu: 2000m, memory: 16Gi}
          requests: {cpu: 2000m, memory: 16Gi}
        securityContext:
        volumeMounts:
        - name: bexhoma-data
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: bexhoma-data
        persistentVolumeClaim:
          claimName: bexhoma-data
  backoffLimit: 4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {app: bexhoma, component: data-source, configuration: default, experiment: default, client: default}
  name: bexhoma-check-data
spec:
  replicas: 1
  selector:
    matchLabels: {app: bexhoma}
  template:
    metadata:
      labels: {app: bexhoma}
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - name: private-registry-auth
      tolerations:
      #- key: "nvidia.com/gpu"
      #  effect: "NoSchedule"
      containers:
      - env:
        image: perdelt/bexhoma:dashboard
        name: data
        volumeMounts:
        - {mountPath: /data, name: bexhoma-data}
      volumes:
      - name: bexhoma-data
        persistentVolumeClaim: {claimName: bexhoma-data}

