apiVersion: batch/v1
kind: Job
metadata:
  labels: {app: bexhoma, component: loading, configuration: default, experiment: default, client: default}
  name: bexhoma-sensor
spec:
  backoffLimit: 4
  completions: 4
  parallelism: 4
  template:
    metadata:
      labels: {app: bexhoma, component: loading, configuration: default, experiment: default, client: default}
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - name: dockerhub
      #- name: private-registry-auth
      nodeSelector: 
      tolerations:
      #- key: "nvidia.com/gpu"
      #  effect: "NoSchedule"
      containers:
      - name: sensor
        #image: bexhoma/generator_hammerdb:4.12
        image: bexhoma/generator_hammerdb:5.0
        imagePullPolicy: Always
        env:
        - {name: BEXHOMA_HOST, value: 'bexhoma-sut-timescaledb-aws-1658676533'}
        - {name: BEXHOMA_PORT, value: '9091'}
        - {name: BEXHOMA_CONNECTION, value: 'monetdb'}
        - {name: BEXHOMA_EXPERIMENT, value: '1234'}
        - {name: PARALLEL, value: '1'}
        - {name: CHILD, value: '1'}
        - {name: SF, value: '1'}
        - {name: RNGSEED, value: '123'}
        - {name: HAMMERDB_TYPE, value: 'mysql'}
        resources:
          #limits: {cpu: 100m}
          #, memory: 16Gi}
          #requests: {cpu: 4000m}
          #, memory: 16Gi}
        #securityContext:
        #  privileged: true
        volumeMounts:
        - name: datadir
          mountPath: "/tmp/tpcc/"
      restartPolicy: Never
      volumes:
      - name: datadir
        emptyDir: {}
