apiVersion: batch/v1
kind: Job
metadata:
  labels: {app: bexhoma, component: benchmarker, configuration: default, experiment: default, client: default}
  name: bexhoma-benchmarker
spec:
  backoffLimit: 4
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels: {app: bexhoma, component: benchmarker, configuration: default, experiment: default, client: default}
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - name: dockerhub
      #- name: private-registry-auth
      nodeSelector: 
      tolerations:
      - key: "nvidia.com/gpu"
        effect: "NoSchedule"
      containers:
      - name: dbmsbenchmarker
        image: bexhoma/benchmarker_hammerdb:4.5
        imagePullPolicy: Always
        env:
        - {name: DBMSBENCHMARKER_CLIENT, value: '1'}
        - {name: DBMSBENCHMARKER_CODE, value: '1611607321'}
        - {name: DBMSBENCHMARKER_SLEEP, value: '60'}
        - {name: DBMSBENCHMARKER_CONNECTION, value: 'MySQL-1'}
        - {name: DBMSBENCHMARKER_ALIAS, value: 'DBMS-A'}
        - {name: BEXHOMA_HOST, value: 'bexhoma-sut-timescaledb-aws-1658676533'}
        - {name: BEXHOMA_PORT, value: '9091'}
        - {name: BEXHOMA_CONNECTION, value: 'monetdb'}
        - {name: BEXHOMA_EXPERIMENT, value: '1234'}
        - {name: PARALLEL, value: '1'}
        - {name: CHILD, value: '1'}
        - {name: SF, value: '1'}
        - {name: RNGSEED, value: '123'}
        - {name: HAMMERDB_VUSERS, value: '1 2 4 8'}
        - {name: HAMMERDB_RAMPUP, value: '2'}
        - {name: HAMMERDB_DURATION, value: '5'}
        - {name: HAMMERDB_ITERATIONS, value: '10000000'}
        - {name: HAMMERDB_TYPE, value: 'postgresql'}
        resources:
          #limits: {cpu: 4000m}
          #, memory: 16Gi}
          #requests: {cpu: 4000m}
          #, memory: 16Gi}
        securityContext:
          privileged: true
        volumeMounts:
        #- name: bexhoma-results
        #  mountPath: /results
      restartPolicy: Never
      volumes:
      #- name: bexhoma-results
      #  persistentVolumeClaim:
      #    claimName: bexhoma-results
