apiVersion: batch/v1
kind: Job
metadata:
  labels: {app: bexhoma, component: loading, configuration: default, experiment: default, client: default}
  name: bexhoma-sensor
spec:
  backoffLimit: 4
  completions: 4
  parallelism: 4
  template:
    metadata:
      labels: {app: bexhoma, component: loading, configuration: default, experiment: default, client: default}
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - name: dockerhub
      #- name: private-registry-auth
      nodeSelector:
        #kubernetes.io/hostname: cl-worker29
      tolerations:
      - key: "nvidia.com/gpu"
        effect: "NoSchedule"
      initContainers:
      - name: datagenerator
        image: bexhoma/generator_tpch:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        env:
        - {name: BEXHOMA_HOST, value: 'bexhoma-sut-monetdb-aws-1658676533'}
        - {name: BEXHOMA_PORT, value: '9091'}
        - {name: BEXHOMA_CONNECTION, value: 'monetdb'}
        - {name: BEXHOMA_EXPERIMENT, value: '1234'}
        - {name: PARALLEL, value: '24'}
        - {name: CHILD, value: '1'}
        - {name: SF, value: '500'}
        - {name: RNGSEED, value: '123'}
        resources:
          #limits: {cpu: 100m}
          #, memory: 16Gi}
          #requests: {cpu: 4000m}
          #, memory: 16Gi}
        volumeMounts:
        - name: datadir
          mountPath: "/tmp/tpch/"
        - {mountPath: /data, name: benchmark-data-volume}
      containers:
      - name: sensor
        image: bexhoma/loader_tpch_monetdb:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        env:
        - {name: BEXHOMA_HOST, value: 'bexhoma-sut-monetdb-aws-1658676533'}
        - {name: BEXHOMA_PORT, value: '9091'}
        - {name: BEXHOMA_CONNECTION, value: 'monetdb'}
        - {name: BEXHOMA_EXPERIMENT, value: '1234'}
        - {name: PARALLEL, value: '24'}
        - {name: CHILD, value: '1'}
        - {name: SF, value: '500'}
        - {name: RNGSEED, value: '123'}
        resources:
          #limits: {cpu: 100m}
          #, memory: 16Gi}
          requests: {cpu: 900m}
          #, memory: 16Gi}
        volumeMounts:
        - name: datadir
          mountPath: "/tmp/tpch/"
        - {mountPath: /data, name: benchmark-data-volume}
      restartPolicy: Never
      volumes:
      - name: datadir
        emptyDir:
          medium: Memory
          #sizeLimit: 10Gi
      - name: benchmark-data-volume
        persistentVolumeClaim: {claimName: bexhoma-data}
