apiVersion: batch/v1
kind: Job
metadata:
  labels: {app: bexhoma, component: benchmarker, configuration: default, experiment: default, client: default}
  name: bexhoma-benchmarker
spec:
  backoffLimit: 4
  completions: 32
  parallelism: 16
  template:
    metadata:
      labels: {app: bexhoma, component: benchmarker, configuration: default, experiment: default, client: default}
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - name: private-registry-auth
      nodeSelector: 
      tolerations:
      - key: "nvidia.com/gpu"
        effect: "NoSchedule"
      containers:
      - name: dbmsbenchmarker
        image: registry.datexis.com/perdelt/bexhoma:dbmsbenchmarker
        imagePullPolicy: Always
        env:
        - {name: DBMSBENCHMARKER_CODE, value: '1611607321'}
        - {name: DBMSBENCHMARKER_SLEEP, value: '60'}
        - {name: DBMSBENCHMARKER_CONNECTION, value: 'MySQL-1'}
        resources:
          limits: {cpu: 2000m, memory: 16Gi}
          requests: {cpu: 2000m, memory: 16Gi}
        securityContext:
          privileged: true
        volumeMounts:
        - name: bexhoma-results
          mountPath: /results
      restartPolicy: Never
      volumes:
      - name: bexhoma-results
        persistentVolumeClaim:
          claimName: bexhoma-results
