apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bexhoma-data
  labels: {app: bexhoma, component: data-source, configuration: default, experiment: default}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: shared
